version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      MONGO_URL: mongodb://db
      NODE_ENV: production
      REDIS_URL: redis://cache
    ports:
      - '5000:5000'
    links:
      - mongo
      - redis

  mongo:
    image: mongo:4.2.8
    container_name: db
    env_file: .env
    volumes:
      - dbdata:/data/db

  redis:
    image: redis:alpine
    container_name: cache
    env_file: .env
    volumes:
      - redis_data:/data

volumes:
  dbdata:
  node_modules:
  redis_data:
